### ISSUE TITLE
咋不更了?

### ISSUE THREAD

**Issue by dmhai** [lim0513/LimLauncher#1]
感觉写的不错，咋不更了?

**Comment by lim0513** [comment]
没啥需求，不知道该加啥了。

**Comment by dmhai** [comment]
这个可以有，这次我来当可恶的产品经理~

[增]右侧图标可以拖动排序(可以拖到别的分类)
[增]窗口在屏幕边缘的时候自动隐藏
[增]右键以管理员方式打开。
[增]右键图标打开程序所在位置

[改]失去焦点的时候，标题栏变色了。
[改]调整左边栏大小的时候，左边最下面一格在闪烁。
[改]托盘图标，不要任务栏图标。
[改]右边图标改成单击打开(可以设置单机/双击更好)

[美]图标不够高清
[美]右边图标的选中样式去掉
[美]添加分组的圆点碍眼，改成右键添加。
[美]左边的滚动条太宽了，而且滚动条上下两端的箭头去掉比较好看。
[美]滚动条改成只有鼠标移过去才出现，当前有种情况：左边分组选中灰色块 + 滚动条箭头灰色块 + 滚动条灰色块 + 标题栏灰色块 + 右侧图标灰色块 ，同时包含N种不一样的灰色，看起来很很很不好看(没图，只能尽量描述了)。


暂时这么多。
老实说，像我这种完美主义的强迫症，我觉得很多地方还可以改。
功能不用很多，但是得顺手 + 顺眼 ^_^

**Comment by lim0513** [comment]
感谢提议。也期待能有人来加入工程共同完善。

**Comment by dmhai** [comment]
这个有点难度，要是BS项目，我或许还能参一脚，CS的我只会拖拖控件，复杂的做不来，不然我早就就自己写了，犯不着买了几年的正版Rolan。

**Comment by fengniange** [comment]
> 没啥需求，不知道该加啥了。

细聊啊，公司有产品希望可以得到师傅帮助，一起完善
