### ISSUE TITLE
bug Windows10系统 1.1或1.2版本，主窗口最小化后，再次打开桌面图标或任务栏固定图标，主窗口都不会再显示，必须双击托盘图标，才能出现窗口，望优化修复，谢谢

### ISSUE THREAD

**Issue by ALEXQWER1** [lim0513/LimLauncher#3]
bug Windows10系统 1.1或1.2版本，主窗口最小化后，再次打开桌面图标或任务栏固定图标，主窗口都不会再显示，必须双击托盘图标，才能出现窗口，（感觉这样好一点，窗口最小化后，出现托盘图标，然后打开桌面图标或任务栏固定图标，程序会像刚启动一样，出现主窗口，方便操作）望优化修复，谢谢，小白一只，无意间发现此软件，感觉界面清爽，功能简单方便，就是很久不更新了，也没见有人提问，自己又解决不了，遂提交此BUG，再次感谢

**Comment by lim0513** [comment]
这个操作相当于是要重新打开一个新程序。程序默认是单例运行，启动的时候判断有在运行的实例就不再重复启动了。

**Comment by lim0513** [comment]
![image](https://user-images.githubusercontent.com/8295174/194679381-8497d8fa-12ad-47b9-800f-bf02c8b5601f.png)

1.3 更新，增加一个【固定状态栏显示】开关

**Comment by ALEXQWER1** [comment]
感谢，已使用
